version: '3.7'
services:
    database:
        image: 'mysql:8.0'
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: news_parser
        ports:
            - '3306'

    rabbitmq:
        image: rabbitmq:3.7-management
        ports: [5672, 15672]
